version: '2'

services:
  summarize-api:
    image: joon09/summarize-bot:0.1
    container_name: summarize-api
    ports:
      - "8989:80"
    environment:
      - TZ=Asia/Seoul
      - OPENAI_API_KEY=apikey
      - MODEL_NAME=gpt-3.5-turbo
      - SPLIT_PAGE=5
      - TIMEOUT=3600
      - KEEP_ALIVE=1800
    restart: always
    volumes:
      - ./data/summarized_files:/app/results:z
      - ./data/pdf_files:/app/uploaded_files:z
    shm_size: "2gb"
